"""Add example_vi to VocabularyEntry

Revision ID: 8e2f5bf0259e
Revises: 547c5ef1e4e9
Create Date: 2025-06-08 23:23:57.613636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2f5bf0259e'
down_revision = '547c5ef1e4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_vi', sa.Text(), nullable=True))

    with op.batch_alter_table('vocabulary_list', schema=None) as batch_op:
        batch_op.drop_column('example_vi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_vi', sa.TEXT(), nullable=True))

    with op.batch_alter_table('vocabulary_entry', schema=None) as batch_op:
        batch_op.drop_column('example_vi')

    # ### end Alembic commands ###
